<a href="https://colab.research.google.com/github/pedrobslima/projeto-ciencia-de-dados/blob/main/especimes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto de Ciência de Dados

Pedro Barros de Souza Lima - pbsl@cin.ufpe.br

Dataset encontrado em: https://opendatasus.saude.gov.br/dataset/febre-amarela-em-humanos-e-primatas-nao-humanos/resource/49169e6d-79cc-4c12-b8b2-ab1428f5bb3f

https://dados.gov.br/dados/conjuntos-dados/fiscalizacao-termo-de-apreensao

###**Objetivos:**

1. Coletar dados	✅

2.	Realizar pré-processamento dos dados:
  * Definição	de	tipos
  * Tratamento	de	dados	ausentes
  * Normalização	e	discretização
  * Limpeza	de	dados	(univariado,	bivariado	e	multivariado)

3.	Apresentar estatísticas descritivas	dos	dados com	visualizações

4.	Realizar teste	de	hipóteses para comparação de	valores	de	categorias	(ex.	preço	m2 em diferentes bairros)	e	visualizar diferenças
* Bônus:
  * Integrar	dados	ou extrair	dados	da	Web
  * Utilizar técnicas não cobertas nas aulas

### **Dicionário de dados:** (ESPÉCIME)

* SEQ_TAD - Chave que identifica o termo de apreensão;
* SEQ_ESPECIME_APREENDIDO - Chave que identifica o espécime apreendido;
* QTD_ESPECIME_APREENDIDO - Quantidade de espécimes apreendidos;
* DES_UNIDADE_MEDIDA - Unidade de medida da quantidade de espécimes apreendidos:
  * m³ (1 MDC); *MDC = Metro de Carvão*
  * Unidade;
  * m³;
  * kg (1.000 L);
  * g (Gramas);
  * m²;
  * Vidro;
  * St.;
  * Metros;
  * nan;
  * Sacos;
  * Caixas;
  * MDC (255 kg ou 7 sacos carvão); *mesmo que "m³ (1 MDC)"??*
  * Feixe;
  * Pares;
  * Litro;
  * M³; *mesmo que "m³", mas não o mesmo que "m³ (1 MDC)"??*
  * Alqueire Mineiro (48.400 m²);
  * Are (100 m²);
  * Arrouba (15 kg);
  * STR (Estéreo); [*possivelmente o mesmo que St.*](https://sistemas.meioambiente.mg.gov.br/reunioes/uploads/fMwr0LLsaIAhBWE7VGBwMTwX7pOygVIU.pdf)
  * Alqueire Paulista (24.200 m²);
* DESCRICAO_PRODUTO - Descrição do produto originado a partir do espécime apreendido:
  * Artesanato;
  * Carne;
  * Casca;
  * Couro;
  * Crânio;
  * Dente;
  * Espécime;
  * Essência;
  * Extrato;
  * Garra;
  * Óleo;
  * Ossos;
  * Ovos;
  * Partes;
  * Pele;
  * Sementes;
  * Subproduto;
  * Taxid. (Empalhado);
* SITUACAO_CARACTERISTICA - Descrição da característica ou situação em que os espécimes foram apreendidos:
  * vivo;
  * morto;
  * abatido;
  * empalhado;
* TIPO - Tipo de infração associada ao espécime apreendido:
  * Degradação;
  * Fauna;
  * Flora;
  * Pesca;
* GRUPO - Identifica o grupo de organismos dos espécimes apreendidos:
  * Anfíbio;
  * Ave;
  * Caranguejo;
  * Domestico;
  * Exótico;
  * Invertebrado;
  * Lagosta;
  * Mamífero;
  * Molusco;
  * Outros;
  * Palmito;
  * Peixes Ornamentais;
  * Pescado;
  * Réptil;
* SEQ_TAXONOMIA - Chave oriunda do sistema Sistaxon, que identifica a taxonomia do espécime apreendido;
* NOME_CIENTIFICO - Nome científico do espécime apreendido;
* DES_NOME_POPULAR - Nome popular do espécime apreendido;
* CITES - Identifica se a espécie do espécime apreendido consta na lista de espécies Cites (Convention on International Trade in Endangered Species of Wild Fauna and Flora):
  * S – Sim;
  * N – Não;
* OBSERVACAO - Descreve demais circunstâncias da apreensão e da situação do espécime;
* DAT_ALTERACAO - Data da última alteração do registro de espécime (ISO 8601);
* ULTIMA_ATUALIZACAO_RELATORIO- Data da última atualização do recurso no portal de dados abertos.
---

### **Dicionário de dados:** (TERMOS DE APREENSÃO)

* SEQ_TAD - Chave que identifica o termo de fiscalização;
* STATUS_FORMULARIO - Situação atual do formulário:
  * Lavrado;
  * Cancelado;
  * Substituído por outro;
  * Excluído;
* SIT_CANCELADO - Indica se o termo encontra-se cancelado:
  * S (Sim);
  * N (Não);
* NUM_TAD - Número impresso no formulário que compõe a identificação do termo juntamente com a série;
* SER_TAD - Caractere impresso no formulário que compõe a identificação do termo juntamente com o número;
* DAT_TAD - Data em que o termo foi lavrado (ISO 8601);
* DAT_IMPRESSAO - Data de impressão do termo no aparelho PDA (ISO 8601);
* NUM_PESSOA_APREENSAO - Número de registro da pessoa no banco de dados do Ibama;
* NOM_PESSOA_APREENSAO - Nome da pessoa responsável pelo bem apreendido;
* CPF_CNPJ_PESSOA_APREENSAO - Número de Cadastro Nacional de Pessoa Jurídica (CNPJ) ou Cadastro de Pessoa Física (CPF) da pessoa responsável pelo bem apreendido;
* NUM_PROCESSO - Número do processo administrativo do Ibama em que será processada a apreensão;
* DES_TAD - Descrição das circunstâncias da apreensão, justificativa e normas que fundamentaram a aplicação da medida;
* COD_MUNICIPIO - Código do município (IBGE) referente ao local da apreensão;
* NOM_MUNICIPIO - Nome do município referente ao local da apreensão;
* SIG_UF - Sigla da unidade da federação referente ao local da apreensão;
* DES_LOCALIZACAO - Descrição do local da apreensão;
* NUM_LONGITUDE_TAD - Longitude do local da apreensão;
* NUM_LATITUDE_TAD - Latitude do local da apreensão;
* FORMA_ENTREGA - Meio empregado para dar ciência da apreensão à pessoa responsável pelo bem apreendido:
  * pessoalmente;
  * representante;
  * aviso de recebimento (AR);
  * edital;
  * o autuado recusou-se a assinar;
* UNID_APRESENTACAO - Unidade responsável pelo recebimento e instauração do processo;
* UNID_CONTROLE - Unidade responsável pelo gerenciamento do termo no sistema de fiscalização;
* VALOR_TAD - Somatória do valor de todos os bens apreendidos identificados no termo;
* SEQ_AUTO_INFRACAO - Chave que identifica o auto de infração vinculado ao termo de apreensão;
* SEQ_NOTIFICACAO - Chave que identifica a notificação vinculada ao termo de apreensão;
* SEQ_ACAO_FISCALIZATORIA - Chave que identifica a ação fiscalizatória em que ocorreu a apreensão;
* NOM_OPERACAO - Nome da operação de fiscalização;
* SEQ_ORDEM_FISCALIZACAO - Chave que identifica a ordem de fiscalização que motivou a ação fiscalizatória;
* NUM_ORDEM_FISCALIZACAO - Identificação da ordem de fiscalização que motivou a ação fiscalizatória, com número de série e estado de origem da unidade que emitiu a ordem;
* SEQ_SOLICITACAO_RECURSO - Chave que identifica a solicitação de recurso vinculada à ordem de fiscalização;
* NUM_SOLICITACAO_RECURSO - Número da solicitação de recurso vinculada à ordem de fiscalização;
* OPERACAO_SOL_RECURSO - Nome da operação de fiscalização descrita na solicitação de recurso;
* DAT_ALTERACAO - Data da última alteração registrada para o termo (ISO 8601);
* TIPO_ALTERACAO - Tipo da última alteração registrada no termo:
  * Redistribuído;
  * Preenchido;
  * Alterado;
  * Cancelado;
  * Cancelamento estornado;
* JUSTIFICATIVA_ALTERACAO - Descrição do motivo da alteração realizada no termo;
* ULTIMA_ATUALIZACAO_RELATORIO - Data da última atualização do recurso no portal de dados abertos.
---

**Dicionário de dados:** (BENS)

* SEQ_TAD - Chave que identifica o termo de apreensão;
* SEQ_BEM_APREENDIDO - Chave que identifica o bem apreendido;
* QTD_BEM_APREENDIDO - Quantidade de bem apreendido;
* DES_UNIDADE_MEDIDA - Unidade de medida da quantidade de bem apreendido;
* DES_TIPO_BEM - Tipo de bem apreendido;
* DES_TIPO_INFRACAO - Tipo da infração associada ao bem apreendido;
* DES_BEM_APREENDIDO - Descrição das características, estado de conservação e demais detalhes do bem apreendido;
* DES_MARCA_MODELO - Marca e modelo do veículo;
* DES_PLACA_VEICULO - Placa de identificação do veículo;
* DES_COR - Cor do veículo;
* CHASSI_NUM_MOTOR - Número do chassi ou número do motor do veículo;
* DES_ANO_VEICULO - Ano de fabricação do veículo;
* DES_LACRE_VEICULO - Número do lacre aposto no veículo apreendido;
* NUM_INSCRICAO_MARINHA - Inscrição ou registro de embarcação na Marinha do Brasil;
* NOME_MATRICULA - Denominação ou número de matrícula do veículo;
* LICENCA_NUMERO_SERIE - Licença ou número de série do veículo;
* DES_FABRICANTE - Fabricante do veículo;
* ULTIMA_ATUALIZACAO_RELATORIO - Data da última atualização do recurso no portal de dados abertos.

**Dicionário de dados:** (ANEXOS)

* SEQ_TAD - Chave que identifica o termo de apreensão;
* SEQ_ANEXO_TAD - Número de registro do anexo;
* TIPO_ANEXO - Tipo de anexo: documento; mapa; foto; croqui;
* DES_ANEXO_TAD - Descrição do anexo;
* NUM_ANEXO_TAD - Número do anexo ou localização no processo administrativo;
* ULTIMA_ATUALIZACAO_RELATORIO - Data da última atualização do recurso no portal de dados abertos.

### Imports

In [1]:
import requests
from http.client import responses
#from os.path import dirname
#from os import environ
#import inspect
#import json
#import gzip
import pandas as pd
import numpy as np
#from time import sleep

## Pré-análise dos dados

In [3]:
dfesp = pd.read_csv("/content/especime_apreendido.csv", sep='\t')

<ipython-input-3-3d80e5232d97>:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  dfesp = pd.read_csv("/content/especime_apreendido.csv", sep='\t')

In [4]:
dfespog = dfesp.copy() # caso precise fazer consultas na versão original depois de modificar o dataset

In [5]:
dfter = pd.read_csv("/content/termo_apreensao.csv", sep=";")

<ipython-input-5-a97b1bcf1c56>:1: DtypeWarning: Columns (0,3,6,9,27,30) have mixed types. Specify dtype option on import or set low_memory=False.
  dfter = pd.read_csv("/content/termo_apreensao.csv", sep=";")

In [12]:
print(dfter.columns[0]+"\n"+dfter.columns[3]+"\n"+dfter.columns[6]+"\n"+dfter.columns[9]+"\n"+dfter.columns[27]+"\n"+dfter.columns[30])

SEQ_TAD
NUM_TAD
DAT_IMPRESSAO
CPF_CNPJ_PESSOA_APREENSAO
NUM_ORDEM_FISCALIZACAO
OPERACAO_SOL_RECURSO

In [13]:
dfesp.columns[13]

'DAT_ALTERACAO'

In [18]:
dfesp.head()

,SEQ_TAD,SEQ_ESPECIME_APREENDIDO,QTD_ESPECIME_APREENDIDO,DES_UNIDADE_MEDIDA,DESCRICAO_PRODUTO,SITUACAO_CARACTERISTICA,TIPO,GRUPO,SEQ_TAXONOMIA,NOME_CIENTIFICO,DES_NOME_POPULAR,CITES,OBSERVACAO,DAT_ALTERACAO,ULTIMA_ATUALIZACAO_RELATORIO
0,1845325,821088,"1,74",m³ (1 MDC),Espécime,Morta,NaN,NaN,34198.0,Dipteryx odorata,NaN,NaN,NaN,NaN,18/05/2024 19:01
1,1845325,821089,"10,31",m³ (1 MDC),Espécime,Morta,NaN,NaN,32970.0,Dipteryx polyphylla,NaN,NaN,NaN,NaN,18/05/2024 19:01
2,1845325,821090,"1,05",m³ (1 MDC),Espécime,Morta,NaN,NaN,32930.0,Cedrela odorata,NaN,NaN,NaN,NaN,18/05/2024 19:01
3,1845319,821087,1,Unidade,Espécime,Viva,NaN,NaN,6427.0,Oryzoborus angolensis,NaN,NaN,NaN,NaN,18/05/2024 19:01
4,1845318,821086,1,Unidade,Espécime,Viva,NaN,NaN,6427.0,Oryzoborus angolensis,NaN,NaN,NaN,NaN,18/05/2024 19:01

In [19]:
dfter.head()

,SEQ_TAD,STATUS_FORMULARIO,SIT_CANCELADO,NUM_TAD,SER_TAD,DAT_TAD,DAT_IMPRESSAO,NUM_PESSOA_APREENSAO,NOM_PESSOA_APREENSAO,CPF_CNPJ_PESSOA_APREENSAO,...,NOM_OPERACAO,SEQ_ORDEM_FISCALIZACAO,NUM_ORDEM_FISCALIZACAO,SEQ_SOLICITACAO_RECURSO,NUM_SOLICITACAO_RECURSO,OPERACAO_SOL_RECURSO,DAT_ALTERACAO,TIPO_ALTERACAO,JUSTIFICATIVA_ALTERACAO,ULTIMA_ATUALIZACAO_RELATORIO
0,1782411,Lavrado,N,371040,C,3005-03-18 16:20:00,NaN,1241919.0,JOSE SANTANA MOTA,23283190500.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-06 17:15:53,Preenchido,TAD Cadastrado,22/05/2024 19:01
1,1465404,Lavrado,N,33353,E,2080-09-01 08:47:17,2080-09-01 09:20:14,236567.0,MUNICIPIO DE JOÃO PESSOA,8806721000103.0,...,NaN,2613087.0,PB033791,NaN,NaN,NaN,2016-06-09 15:49:09,NaN,NaN,22/05/2024 19:01
2,144855,Lavrado,N,384670,C,2051-06-03 14:20:00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2012-10-01 15:01:21,Preenchido,TAD Cadastrado,22/05/2024 19:01
3,1841246,Lavrado,N,WFPLW5SL,NaN,2024-11-30 17:27:41,NaN,8556848.0,Thiago da Silva Lima,3793467295.0,...,NaN,7786608.0,AM076560,51324.0,51324.2023,BANZEIRO,2024-03-07 15:55:07,Alterado,(Migração AI-e) TAD Alterado,22/05/2024 19:01
4,1841245,Lavrado,N,GDLQ1VZX,NaN,2024-11-30 16:55:41,NaN,8556848.0,Thiago da Silva Lima,3793467295.0,...,NaN,7786608.0,AM076560,51324.0,51324.2023,BANZEIRO,2024-03-07 15:55:06,Alterado,(Migração AI-e) TAD Alterado,22/05/2024 19:01

NaN = Not a Number

NaT = Not a Time

In [16]:
print(len(dfesp))
len(dfter)

138742

151699

In [20]:
df = pd.merge(dfesp, dfter, how='inner', on='SEQ_TAD')

In [21]:
len(df)

42293

In [24]:
df.dtypes

SEQ_TAD                            object
SEQ_ESPECIME_APREENDIDO             int64
QTD_ESPECIME_APREENDIDO            object
DES_UNIDADE_MEDIDA                 object
DESCRICAO_PRODUTO                  object
SITUACAO_CARACTERISTICA            object
TIPO                               object
GRUPO                              object
SEQ_TAXONOMIA                     float64
NOME_CIENTIFICO                    object
DES_NOME_POPULAR                   object
CITES                              object
OBSERVACAO                         object
DAT_ALTERACAO_x                    object
ULTIMA_ATUALIZACAO_RELATORIO_x     object
STATUS_FORMULARIO                  object
SIT_CANCELADO                      object
NUM_TAD                            object
SER_TAD                            object
DAT_TAD                            object
DAT_IMPRESSAO                      object
NUM_PESSOA_APREENSAO              float64
NOM_PESSOA_APREENSAO               object
CPF_CNPJ_PESSOA_APREENSAO          object
NUM_PROCESSO                      float64
DES_TAD                            object
COD_MUNICIPIO                     float64
NOM_MUNICIPIO                      object
SIG_UF                             object
DES_LOCALIZACAO                    object
NUM_LONGITUDE_TAD                  object
NUM_LATITUDE_TAD                   object
FORMA_ENTREGA                      object
UNID_APRESENTACAO                  object
UNID_CONTROLE                      object
VALOR_TAD                          object
SEQ_AUTO_INFRACAO                 float64
SEQ_NOTIFICACAO                   float64
SEQ_ACAO_FISCALIZATORIA           float64
NOM_OPERACAO                       object
SEQ_ORDEM_FISCALIZACAO            float64
NUM_ORDEM_FISCALIZACAO             object
SEQ_SOLICITACAO_RECURSO           float64
NUM_SOLICITACAO_RECURSO           float64
OPERACAO_SOL_RECURSO               object
DAT_ALTERACAO_y                    object
TIPO_ALTERACAO                     object
JUSTIFICATIVA_ALTERACAO            object
ULTIMA_ATUALIZACAO_RELATORIO_y     object
dtype: object

###SEQ_TAD

In [ ]:
df["SEQ_TAD"].nunique()

53037

In [ ]:
df["SEQ_TAD"].isna().any()

False

###SEQ_ESPECIME_APREENDIDO

In [ ]:
df["SEQ_ESPECIME_APREENDIDO"].nunique()

138742

In [ ]:
df["SEQ_ESPECIME_APREENDIDO"].isna().any()

False

###QTD_ESPECIME_APREENDIDO & DES_UNIDADE_MEDIDA

Análise só de QTD_ESPECIME_APREENDIDO:

In [ ]:
df["QTD_ESPECIME_APREENDIDO"].dtypes

dtype('O')

In [ ]:
df["QTD_ESPECIME_APREENDIDO"].isna().any()

True

In [ ]:
df[df["QTD_ESPECIME_APREENDIDO"].isna()].head()

,SEQ_TAD,SEQ_ESPECIME_APREENDIDO,QTD_ESPECIME_APREENDIDO,DES_UNIDADE_MEDIDA,DESCRICAO_PRODUTO,SITUACAO_CARACTERISTICA,TIPO,GRUPO,SEQ_TAXONOMIA,NOME_CIENTIFICO,DES_NOME_POPULAR,CITES,OBSERVACAO,DAT_ALTERACAO,ULTIMA_ATUALIZACAO_RELATORIO
1886,1833978,818295,NaN,NaN,Partes,Morto,Pesca,Lagosta,382669.0,Panulirus argus,NaN,N,NaN,NaN,18/05/2024 19:01
1887,1833978,818296,NaN,NaN,Partes,Morto,Pesca,Lagosta,382666.0,Panulirus laevicauda,NaN,N,NaN,NaN,18/05/2024 19:01
17522,1779784,796416,NaN,m³,NaN,Morta,Flora,NaN,33208.0,Tabebuia serratifolia,Ipê,N,madeira serrada,NaN,18/05/2024 19:01
17523,1779784,796417,NaN,m³,NaN,Morta,Flora,NaN,34771.0,Chrysophyllum spp.,Abiurana,N,madeira serrada,NaN,18/05/2024 19:01
20783,1739462,787910,NaN,NaN,NaN,Morto,Pesca,Pescado,NaN,NaN,Piauçu,N,53 kg,NaN,18/05/2024 19:01

In [ ]:
np.isnan(df.iloc[1886]["QTD_ESPECIME_APREENDIDO"])

True

In [ ]:
df["QTD_ESPECIME_APREENDIDO"].nunique()

8463

Análise apenas de DES_UNIDADE_MEDIDA:

In [ ]:
df["DES_UNIDADE_MEDIDA"].unique()

array(['m³ (1 MDC)', 'Unidade', 'm³', 'kg (1.000 L)', 'g (Gramas)', 'm²',
       'Vidro', 'St.', 'Metros', nan, 'Sacos', 'Caixas',
       'MDC (255 kg ou 7 sacos carvão)', 'Feixe', 'Pares', 'Litro', 'M³',
       'Alqueire Mineiro (48.400 m²)', 'Are (100 m²)', 'Arrouba (15 kg)',
       'STR (Estéreo)', 'Alqueire Paulista (24.200 m²)'], dtype=object)

In [ ]:
df["DES_UNIDADE_MEDIDA"].nunique()

21

Análise conjunta:

In [ ]:
(df["QTD_ESPECIME_APREENDIDO"].isna() == df["DES_UNIDADE_MEDIDA"].isna()).value_counts()

True     135837
False      2905
Name: count, dtype: int64

In [ ]:
mask1 = df['QTD_ESPECIME_APREENDIDO'].isna()
mask2 = df['DES_UNIDADE_MEDIDA'].isna()
mask3 = (mask1 | mask2) & ~(mask1 & mask2) # xor
mask4 = ~(mask1) & mask2 # se a qtd não é NAN, mas a unidade sim
mask5 = mask1 & ~(mask2) # se qtd é NAN, mas a unidade não

In [ ]:
print(f'''xor:\t\t\t{len(df[mask3])}
QTD!=NA & UND=NA:\t{len(df[mask4])}
QTD=NA & UND!=NA:\t{len(df[mask5])}''')

xor:			2905
QTD!=NA & UND=NA:	2422
QTD=NA & UND!=NA:	483

No caso da ```mask4```, dá para tentar dar um palpite adequado sobre a unidade de medida que está faltando vendo qual o espécime, tipo e, possivelmente, o valor da quantidade

In [ ]:
df[mask4].loc[:, 'TIPO'].value_counts()

TIPO
Fauna    2032
Pesca     149
Name: count, dtype: int64

In [ ]:
mask6 = ~(mask1) & ~(mask2)

In [ ]:
# transformando em floats, menos os <NAN>, dps lido com eles
df["QTD_ESPECIME_APREENDIDO"] = df["QTD_ESPECIME_APREENDIDO"].apply(lambda x: float(x.replace(',', '.')) if type(x)==str else np.NAN)

In [ ]:
cols = ['QTD_ESPECIME_APREENDIDO', 'DES_UNIDADE_MEDIDA']#, 'GRUPO', 'SITUACAO_CARACTERISTICA']
df[(df['TIPO'] == 'Fauna') & (mask6)].loc[:, cols].groupby(by='DES_UNIDADE_MEDIDA').aggregate('median')#.head()

                               QTD_ESPECIME_APREENDIDO
DES_UNIDADE_MEDIDA
Alqueire Mineiro (48.400 m²)                     3.000
Alqueire Paulista (24.200 m²)                   40.000
Are (100 m²)                                     1.000
Arrouba (15 kg)                                  1.000
Caixas                                           1.000
Feixe                                            6.000
M³                                               1.500
Pares                                            9.000
STR (Estéreo)                                    1.500
Sacos                                            5.000
St.                                              3.000
Unidade                                          1.000
Vidro                                           14.500
g (Gramas)                                       6.000
kg (1.000 L)                                    12.000
m³                                               6.055
m³ (1 MDC)                                      14.640

In [ ]:
cols = ['DES_UNIDADE_MEDIDA', 'GRUPO']#, 'SITUACAO_CARACTERISTICA']
df[(df['TIPO'] == 'Fauna') & (mask6) & (df['GRUPO'].notna())].loc[:, cols].groupby(by='GRUPO').value_counts()

GRUPO         DES_UNIDADE_MEDIDA
Anfíbio       Unidade                            309
              kg (1.000 L)                        46
              g (Gramas)                          12
              Pares                                1
              Feixe                                1
Ave           Unidade                          41854
              kg (1.000 L)                        36
              g (Gramas)                          26
              M³                                  18
              Pares                               12
              Alqueire Mineiro (48.400 m²)         4
              Sacos                                3
              Vidro                                3
              Alqueire Paulista (24.200 m²)        3
              STR (Estéreo)                        3
              Feixe                                2
              St.                                  2
              Caixas                               2
Domestico     Unidade                            163
              kg (1.000 L)                         1
Exótico       Unidade                             61
              kg (1.000 L)                         3
Invertebrado  Unidade                            224
              kg (1.000 L)                        68
              Caixas                               7
              g (Gramas)                           3
              M³                                   2
              Vidro                                1
Mamífero      Unidade                           1955
              kg (1.000 L)                       148
              Pares                               10
              g (Gramas)                           9
              m³                                   1
              Sacos                                1
              M³                                   1
              Caixas                               1
              Are (100 m²)                         1
              Alqueire Mineiro (48.400 m²)         1
Réptil        Unidade                           1657
              kg (1.000 L)                        22
              g (Gramas)                           7
              Pares                                4
              Vidro                                1
              Sacos                                1
Name: count, dtype: int64

Mas para o inverso, ou seja, casos em que a quantidade é ```<NAN>```, já não é tão fácil dar esse palpite, então talvez seja melhor usar outras técnicas. Se possível, não deletar essas entradas

In [ ]:
df[mask5].loc[:, 'TIPO'].value_counts()

TIPO
Fauna    343
Flora     99
Pesca     41
Name: count, dtype: int64

In [ ]:
df['QTD_ESPECIME_APREENDIDO'].apply(lambda x: type(x)==float).all()

True

In [ ]:
df['QTD_ESPECIME_APREENDIDO'].isna().any()

False

In [ ]:
df["DES_UNIDADE_MEDIDA"].isna().any()

True

###DESCRICAO_PRODUTO:

In [ ]:
df["MUN_OCOR"].nunique()

591

In [ ]:
df["MUN_OCOR"].isna().any()

False

In [ ]:
view = df[["MUN_OCOR", "COD_MUN_OCOR"]].groupby(by="MUN_OCOR").aggregate("mean")

view["COD_MUN_OCOR"] = view["COD_MUN_OCOR"].apply(lambda x: x in df["COD_MUN_OCOR"].unique())

view[view["COD_MUN_OCOR"] == False]

           COD_MUN_OCOR
MUN_OCOR
PALMAS            False
PALMEIRA          False
VERA CRUZ         False

In [ ]:
anomalias = view[view["COD_MUN_OCOR"] == False].index

df[df["MUN_OCOR"].isin(anomalias)].loc[:, ["UF_OCOR", "MUN_OCOR", "COD_MUN_OCOR", "DATA_OCOR"]].sort_values(by=["MUN_OCOR", "DATA_OCOR"])

     UF_OCOR   MUN_OCOR  COD_MUN_OCOR  DATA_OCOR
ID
254       TO     PALMAS        172100 2015-07-25
795       TO     PALMAS        172100 2017-09-29
1301      TO     PALMAS        172100 2018-01-18
2134      PR     PALMAS        411760 2020-11-18
2166      PR     PALMAS        411760 2020-11-30
2167      PR     PALMAS        411760 2020-11-30
2168      PR     PALMAS        411760 2020-12-09
1993      PR   PALMEIRA        411770 2019-12-05
2150      SC   PALMEIRA        421205 2021-01-19
2152      SC   PALMEIRA        421205 2021-01-24
2153      SC   PALMEIRA        421205 2021-01-24
2154      SC   PALMEIRA        421205 2021-01-24
2260      SC   PALMEIRA        421205 2021-02-08
111       RS  VERA CRUZ        432270 2009-03-27
209       RS  VERA CRUZ        432270 2009-04-14
222       RS  VERA CRUZ        432270 2009-04-29
560       BA  VERA CRUZ        293320 2017-03-22
570       BA  VERA CRUZ        293320 2017-03-27

Parece que são cidades de nomes iguais, mas estados diferentes.

* Palmas: TO e PR
* Palmeira: SC e PR
* Vera Cruz: RS e BA

###SITUACAO_CARACTERISTICA:

In [ ]:
df["DATA_OCOR"].isna().any()

True

In [ ]:
df[df["DATA_OCOR"].isna() == True]

,MACRORREG_OCOR,COD_UF_OCOR,UF_OCOR,COD_MUN_OCOR,MUN_OCOR,DATA_OCOR,SE_OCOR,MES_OCOR,ANO_OCOR,MONITORAMENTO_OCOR
ID,,,,,,,,,,
1,CO,52,GO,521100,ITAPIRAPUÃ,NaT,NaN,2.0,2000,1999/2000
2,CO,52,GO,521970,SANTA TEREZINHA DE GOIÁS,NaT,NaN,NaN,2000,1999/2000
3,CO,52,GO,521520,NOVO BRASIL,NaT,NaN,2.0,2000,1999/2000
4,SE,31,MG,310450,ARINOS,NaT,NaN,2.0,2000,1999/2000
5,SE,31,MG,310820,BONFINÓPOLIS DE MINAS,NaT,NaN,4.0,2000,1999/2000
6,SE,31,MG,313862,LIMEIRA DO OESTE,NaT,NaN,7.0,2001,2000/2001
7,S,43,RS,431770,SANTO ANTÔNIO DAS MISSÕES,NaT,NaN,6.0,2001,2000/2001
8,S,43,RS,430865,GARRUCHOS,NaT,NaN,5.0,2001,2000/2001
10,SE,31,MG,315980,SANTA VITÓRIA,NaT,NaN,11.0,2002,2002/2003
11,S,43,RS,431740,SANTIAGO,NaT,NaN,1.0,2003,2002/2003
703,N,11,RO,110020,PORTO VELHO,NaT,NaN,NaN,2017,2016/2017
1560,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1561,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1562,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1563,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1564,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1565,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1566,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1567,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1568,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1569,SE,35,SP,352590,JUNDIAÍ,NaT,NaN,NaN,2017,2017/2018
1570,SE,35,SP,353760,PERUÍBE,NaT,NaN,NaN,2018,2017/2018

###TIPO:

###GRUPO:

###SEQ_TAXONOMIA:

###NOME_CIENTIFICO:

###DES_NOME_POPULAR:

###CITES:

###OBSERVACAO:

###DAT_ALTERACAO:

###ULTIMA_ATUALIZACAO_RELATORIO:

## Pré-análise dos dados (ANTIGO)

In [ ]:
df = pd.read_csv("/content/febre_amarela_macacos.csv", encoding="ISO 8859-1", sep=';', index_col="ID")

O arquivo original foi escrito como ISO 8859-1 ao invés de UTF-8. Uma dos motivos é que a coleta de dados vêm ocorrendo desde 1999

In [ ]:
df.DATA_OCOR = pd.to_datetime(df.DATA_OCOR, dayfirst=True)

(precisa converter o formato das datas para o pandas não lançar avisos)

In [ ]:
df.head(15)

,MACRORREG_OCOR,COD_UF_OCOR,UF_OCOR,COD_MUN_OCOR,MUN_OCOR,DATA_OCOR,SE_OCOR,MES_OCOR,ANO_OCOR,MONITORAMENTO_OCOR
ID,,,,,,,,,,
1,CO,52,GO,521100,ITAPIRAPUÃ,NaT,NaN,2.0,2000,1999/2000
2,CO,52,GO,521970,SANTA TEREZINHA DE GOIÁS,NaT,NaN,NaN,2000,1999/2000
3,CO,52,GO,521520,NOVO BRASIL,NaT,NaN,2.0,2000,1999/2000
4,SE,31,MG,310450,ARINOS,NaT,NaN,2.0,2000,1999/2000
5,SE,31,MG,310820,BONFINÓPOLIS DE MINAS,NaT,NaN,4.0,2000,1999/2000
6,SE,31,MG,313862,LIMEIRA DO OESTE,NaT,NaN,7.0,2001,2000/2001
7,S,43,RS,431770,SANTO ANTÔNIO DAS MISSÕES,NaT,NaN,6.0,2001,2000/2001
8,S,43,RS,430865,GARRUCHOS,NaT,NaN,5.0,2001,2000/2001
9,S,43,RS,431110,JAGUARI,2002-11-14,46.0,11.0,2002,2002/2003
10,SE,31,MG,315980,SANTA VITÓRIA,NaT,NaN,11.0,2002,2002/2003
11,S,43,RS,431740,SANTIAGO,NaT,NaN,1.0,2003,2002/2003
12,CO,52,GO,520140,APARECIDA DE GOIÂNIA,2007-10-01,40.0,10.0,2007,2007/2008
13,CO,52,GO,520140,APARECIDA DE GOIÂNIA,2007-12-01,48.0,12.0,2007,2007/2008
14,CO,52,GO,520140,APARECIDA DE GOIÂNIA,2008-10-08,41.0,10.0,2008,2008/2009
15,CO,52,GO,520140,APARECIDA DE GOIÂNIA,2008-01-01,1.0,1.0,2008,2007/2008

NaN = Not a Number

NaT = Not a Time

In [ ]:
df.dtypes

MACRORREG_OCOR                object
COD_UF_OCOR                    int64
UF_OCOR                       object
COD_MUN_OCOR                   int64
MUN_OCOR                      object
DATA_OCOR             datetime64[ns]
SE_OCOR                      float64
MES_OCOR                     float64
ANO_OCOR                       int64
MONITORAMENTO_OCOR            object
dtype: object

###MACRORREG_OCOR:

In [ ]:
df["MACRORREG_OCOR"].unique()

array(['CO', 'SE', 'S', 'N', 'NE'], dtype=object)

In [ ]:
df["MACRORREG_OCOR"] = df["MACRORREG_OCOR"].astype("category")

In [ ]:
df["MACRORREG_OCOR"].cat.categories

Index(['CO', 'N', 'NE', 'S', 'SE'], dtype='object')

###COD_UF_OCOR:

In [ ]:
df["COD_UF_OCOR"].nunique() == df["UF_OCOR"].nunique()

False

###UF_OCOR:

In [ ]:
df["UF_OCOR"].unique()

array(['GO', 'MG', 'RS', 'DF', 'MS', 'SP', 'TO', 'PR', 'ES', 'PA', 'BA',
       'MT', 'RR', 'RJ', 'RO', 'SC', 'pr', 'AC'], dtype=object)

O Paraná possui 2 siglas, 'PR' e 'pr'

In [ ]:
df['UF_OCOR'] = df['UF_OCOR'].apply(lambda x: x.upper())

In [ ]:
df["UF_OCOR"] = df["UF_OCOR"].astype('category')

In [ ]:
print(df["COD_UF_OCOR"].nunique() == len(df["UF_OCOR"].cat.categories), '\n')
df["UF_OCOR"].value_counts()

True

UF_OCOR
SP    859
PR    400
RS    307
MG    266
SC    254
RJ     91
ES     81
GO     73
BA     48
DF     27
PA     23
TO     15
MT      8
RR      4
MS      2
RO      1
AC      1
Name: count, dtype: int64

###COD_MUN_OCOR:

In [ ]:
print(df["COD_MUN_OCOR"].nunique())
df["COD_MUN_OCOR"].nunique() == df["MUN_OCOR"].nunique()

594

False

In [ ]:
df["COD_MUN_OCOR"].isna().any()

False

###MUN_OCOR:

In [ ]:
df["MUN_OCOR"].nunique()

591

In [ ]:
df["MUN_OCOR"].isna().any()

False

In [ ]:
view = df[["MUN_OCOR", "COD_MUN_OCOR"]].groupby(by="MUN_OCOR").aggregate("mean")

view["COD_MUN_OCOR"] = view["COD_MUN_OCOR"].apply(lambda x: x in df["COD_MUN_OCOR"].unique())

view[view["COD_MUN_OCOR"] == False]

           COD_MUN_OCOR
MUN_OCOR
PALMAS            False
PALMEIRA          False
VERA CRUZ         False

In [ ]:
anomalias = view[view["COD_MUN_OCOR"] == False].index

df[df["MUN_OCOR"].isin(anomalias)].loc[:, ["UF_OCOR", "MUN_OCOR", "COD_MUN_OCOR", "DATA_OCOR"]].sort_values(by=["MUN_OCOR", "DATA_OCOR"])

     UF_OCOR   MUN_OCOR  COD_MUN_OCOR  DATA_OCOR
ID
254       TO     PALMAS        172100 2015-07-25
795       TO     PALMAS        172100 2017-09-29
1301      TO     PALMAS        172100 2018-01-18
2134      PR     PALMAS        411760 2020-11-18
2166      PR     PALMAS        411760 2020-11-30
2167      PR     PALMAS        411760 2020-11-30
2168      PR     PALMAS        411760 2020-12-09
1993      PR   PALMEIRA        411770 2019-12-05
2150      SC   PALMEIRA        421205 2021-01-19
2152      SC   PALMEIRA        421205 2021-01-24
2153      SC   PALMEIRA        421205 2021-01-24
2154      SC   PALMEIRA        421205 2021-01-24
2260      SC   PALMEIRA        421205 2021-02-08
111       RS  VERA CRUZ        432270 2009-03-27
209       RS  VERA CRUZ        432270 2009-04-14
222       RS  VERA CRUZ        432270 2009-04-29
560       BA  VERA CRUZ        293320 2017-03-22
570       BA  VERA CRUZ        293320 2017-03-27

Parece que são cidades de nomes iguais, mas estados diferentes.

* Palmas: TO e PR
* Palmeira: SC e PR
* Vera Cruz: RS e BA

###DATA_OCOR:

In [ ]:
df["DATA_OCOR"].isna().any()

True

In [ ]:
df[df["DATA_OCOR"].isna() == True]

,MACRORREG_OCOR,COD_UF_OCOR,UF_OCOR,COD_MUN_OCOR,MUN_OCOR,DATA_OCOR,SE_OCOR,MES_OCOR,ANO_OCOR,MONITORAMENTO_OCOR
ID,,,,,,,,,,
1,CO,52,GO,521100,ITAPIRAPUÃ,NaT,NaN,2.0,2000,1999/2000
2,CO,52,GO,521970,SANTA TEREZINHA DE GOIÁS,NaT,NaN,NaN,2000,1999/2000
3,CO,52,GO,521520,NOVO BRASIL,NaT,NaN,2.0,2000,1999/2000
4,SE,31,MG,310450,ARINOS,NaT,NaN,2.0,2000,1999/2000
5,SE,31,MG,310820,BONFINÓPOLIS DE MINAS,NaT,NaN,4.0,2000,1999/2000
6,SE,31,MG,313862,LIMEIRA DO OESTE,NaT,NaN,7.0,2001,2000/2001
7,S,43,RS,431770,SANTO ANTÔNIO DAS MISSÕES,NaT,NaN,6.0,2001,2000/2001
8,S,43,RS,430865,GARRUCHOS,NaT,NaN,5.0,2001,2000/2001
10,SE,31,MG,315980,SANTA VITÓRIA,NaT,NaN,11.0,2002,2002/2003
11,S,43,RS,431740,SANTIAGO,NaT,NaN,1.0,2003,2002/2003
703,N,11,RO,110020,PORTO VELHO,NaT,NaN,NaN,2017,2016/2017
1560,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1561,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1562,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1563,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1564,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1565,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1566,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1567,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1568,SE,35,SP,351970,IBIÚNA,NaT,NaN,NaN,2018,2017/2018
1569,SE,35,SP,352590,JUNDIAÍ,NaT,NaN,NaN,2017,2017/2018
1570,SE,35,SP,353760,PERUÍBE,NaT,NaN,NaN,2018,2017/2018

###SE_OCOR:

###MES_OCOR:

###ANO_OCOR:

###MONITORAMENTO_OCOR:

# Caso queira baixar o dataset em UTF-8:

Original:

In [ ]:
with open("/content/febre_amarela_macacos (1).csv", "w", encoding="utf-8") as new_dtsus:
  with open("/content/febre_amarela_macacos.csv", "r", encoding="ISO 8859-1") as dtsus:
    new_dtsus.write(dtsus.read())

Tratado:

In [ ]:
df.to_csv(r"/content/febre_amarela_macacos (1).csv")